# Permalinks
permalink:           pretty

# Setup
title:               Brent's Blog
tagline:             Brent's Data Science Blog
url:                 http://brendenrossin.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Brent Rossin
  email:             brendenrossin@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/brendenrossin

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'

theme: jekyll-theme-cayman